# SVD

### Theory


$A = U \Sigma V^T$

$A$ is an $m \times n$ matrix

$U$ is an $m \times n$ orthogonal matrix

$\Sigma$ is an $n \times n$ diagonal matrix

$V$ is an $n \times n$ orthogonal matrix

The diagonal values in the Sigma matrix are known as the singular values of the original matrix A. The columns of the U matrix are called the left-singular vectors of A, and the columns of V are called the right-singular vectors of A.

### NumPy SVD

In [1]:
from numpy import array
from numpy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
U, S, V = svd(A)
print(A)
print()
print(U)
print()
print(S)
print()
print(V)

[[1 2]
 [3 4]
 [5 6]]

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

[9.52551809 0.51430058]

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


### Reconstruction

In [2]:
from numpy import diag
from numpy import dot
from numpy import zeros

# create m x n Z matrix
Z = zeros((A.shape[0], A.shape[1]))

# populate Z with n x n diagonal matrix
Z[:A.shape[1], :A.shape[1]] = diag(S)

print(Z)
print()

B = U.dot(Z.dot(V))
print(B)

[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [3]:
# define a matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

U, S, V = svd(A)
# create n x n Sigma matrix
Z = diag(S)
# reconstruct matrix
B = U.dot(Z.dot(V))
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Pseudoinverse

In [4]:
from numpy.linalg import pinv
A = array([[1, 2], [3, 4], [5, 6]])
print(pinv(A))

[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


### Pseudoinverse by SVD

$A^{-1} = V \Sigma^{-1} U^T$

In [5]:
A = array([[0.1, 0.2],[0.3, 0.4],[0.5, 0.6],[0.7, 0.8]])
print(A)
U, S, V = svd(A)
d = 1.0 / S
D = zeros(A.shape)
D[:A.shape[1], :A.shape[1]] = diag(d)
B = V.T.dot(D.T).dot(U.T)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  1.42663659e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


### Equations Solving

$A x = b \Rightarrow x = A^{-1}b$

$U \Sigma V^{T}x = b$

$\Sigma V^{T}x = U^{T}b, \ let \ w = V^{T}x \ and \ c = U^{T}b$

$\Sigma w = c$

$V^T x = w$

In [6]:
from numpy import * 
A = floor(random.rand(4,4)*20-10) # generating a random
b = floor(random.rand(4,1)*20-10) # system Ax=b

U,s,V = linalg.svd(A) # SVD decomposition of A

# computing the inverse using pinv
# computing the inverse using the SVD decomposition
inv_svd = dot(dot(V.T,linalg.inv(diag(s))),U.T)


x = linalg.solve(A,b) # solve Ax=b using linalg.solve

x_svd = dot(inv_svd,b) # solving Ax=b computing x = A^-1*b

print(x)
print()
print(x_svd)

[[1.78429681]
 [2.92493529]
 [3.47152718]
 [0.28170837]]

[[1.78429681]
 [2.92493529]
 [3.47152718]
 [0.28170837]]


### Dimensionality Reduction

Data with a large number of features, such as more features (columns) than observations (rows) may be reduced to a smaller subset of features that are most relevant to the prediction problem.

The result is a matrix with a lower rank that is said to approximate the original matrix

In [7]:
# define a matrix
A = array([
[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])
print(A)
# Singular-value decomposition
U, S, V = svd(A)
# create m x n Sigma matrix
Z = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Z[:A.shape[0], :A.shape[0]] = diag(S)
# select
n = 2
Z = Z[:, :n]
V = V[:n, :]
# reconstruct
B = U.dot(Z.dot(V))
print(B)
# transform
T = U.dot(Z)
print(T)
T = A.dot(VT.T)
print(T)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


NameError: name 'VT' is not defined

### Check sklearn.decomposition

In [8]:
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=2)
svd.fit(A)
result = svd.transform(A)
print(result)

[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]
